In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
# df = pd.read_csv("/content/drive/MyDrive/code/vgsales.csv") # The "read_csv()" function returns a data frame objects which is like an excel spreadsheet
music_df = pd.read_csv("/content/drive/MyDrive/code/python projects/personalized_music_recommendation_dataset.csv")
music_df # to inspect

,timestamp,user_id,age,gender,location,device_type,listening_time_mins,sessions_per_day,time_of_day,day_of_week,...,skip_count,added_to_playlist,finished_song,time_spent_on_song,repeat_count,first_time_listening,context_type,song_position_in_session,session_duration_mins,liked
0,2021-01-01 00:00:00,1040,35,Female,US,Mobile,3,2,Afternoon,Weekday,...,2,0,1,109,1,0,Relax,10,31,0
1,2021-01-01 00:30:00,1000,45,Male,US,Mobile,28,1,Evening,Weekday,...,1,1,1,116,1,0,Workout,6,38,0
2,2021-01-01 01:00:00,1025,35,Other,US,Mobile,65,3,Afternoon,Weekday,...,0,0,0,172,1,0,Workout,8,25,1
3,2021-01-01 01:30:00,1049,45,Male,US,Smart Speaker,2,1,Afternoon,Weekend,...,0,0,1,172,0,1,Relax,8,49,0
4,2021-01-01 02:00:00,1011,45,Male,UK,Mobile,44,1,Evening,Weekday,...,0,1,0,178,1,0,Relax,2,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70124,2024-12-31 22:00:00,1039,35,Male,IN,Mobile,0,1,Evening,Weekday,...,0,0,1,198,1,0,Commute,5,24,0
70125,2024-12-31 22:30:00,1033,55,Female,UK,Mobile,38,2,Afternoon,Weekday,...,0,0,1,118,3,1,Study,1,24,1
70126,2024-12-31 23:00:00,1029,55,Male,DE,Desktop,27,1,Evening,Weekend,...,3,0,1,161,0,0,Relax,2,45,1
70127,2024-12-31 23:30:00,1037,35,Male,US,Mobile,3,1,Afternoon,Weekday,...,2,0,1,131,1,1,Party,4,13,1
70128,2025-01-01 00:00:00,1040,35,Female,US,Mobile,4,1,Afternoon,Weekday,...,2,0,0,134,0,0,Workout,4,28,1

In [ ]:
type(music_df)

pandas.core.frame.DataFrame

In [ ]:
music_df.shape # This will return the shape of the data frame. Rows and columns in a tuple (rows, columns) .

(70129, 49)

In [ ]:
music_df.describe() # With the ".describe()" method we will get statistic info about each column of data frame.

,user_id,age,listening_time_mins,sessions_per_day,recent_skip_rate,song_id,release_year,duration_sec,popularity,tempo,...,play_count,skip_count,added_to_playlist,finished_song,time_spent_on_song,repeat_count,first_time_listening,song_position_in_session,session_duration_mins,liked
count,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,...,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000,70129.000000
mean,1024.530508,35.282351,19.501961,1.523592,0.285876,10099.389397,2018.799655,209.463489,49.569622,119.927511,...,4.986910,0.994068,0.198220,0.699768,159.301231,0.994382,0.399749,5.489940,29.593392,0.298122
std,14.474660,10.439658,20.035027,0.729316,0.159505,57.697092,4.014108,59.920928,28.883892,14.974337,...,2.232181,0.997870,0.398662,0.458362,30.026655,0.998000,0.489850,2.871212,9.978299,0.457437
min,1000.000000,18.000000,0.000000,1.000000,0.001540,10000.000000,2010.000000,-74.000000,0.000000,56.870131,...,0.000000,0.000000,0.000000,0.000000,35.000000,0.000000,0.000000,1.000000,-13.000000,0.000000
25%,1012.000000,25.000000,5.000000,1.000000,0.161633,10049.000000,2016.000000,169.000000,25.000000,109.830796,...,3.000000,0.000000,0.000000,0.000000,139.000000,0.000000,0.000000,3.000000,23.000000,0.000000
50%,1025.000000,35.000000,13.000000,1.000000,0.265101,10100.000000,2019.000000,209.000000,50.000000,120.005073,...,5.000000,1.000000,0.000000,1.000000,159.000000,1.000000,0.000000,5.000000,30.000000,0.000000
75%,1037.000000,45.000000,27.000000,2.000000,0.388704,10149.000000,2022.000000,250.000000,75.000000,130.138337,...,6.000000,2.000000,0.000000,1.000000,179.000000,2.000000,1.000000,8.000000,36.000000,1.000000
max,1049.000000,55.000000,204.000000,4.000000,0.946192,10199.000000,2024.000000,491.000000,99.000000,181.040198,...,17.000000,8.000000,1.000000,1.000000,295.000000,8.000000,1.000000,10.000000,74.000000,1.000000

In [ ]:
music_df.values #This attribute returns a two dimension array.

array([['2021-01-01 00:00:00', 1040, 35, ..., 10, 31, 0],
       ['2021-01-01 00:30:00', 1000, 45, ..., 6, 38, 0],
       ['2021-01-01 01:00:00', 1025, 35, ..., 8, 25, 1],
       ...,
       ['2024-12-31 23:00:00', 1029, 55, ..., 2, 45, 1],
       ['2024-12-31 23:30:00', 1037, 35, ..., 4, 13, 1],
       ['2025-01-01 00:00:00', 1040, 35, ..., 4, 28, 1]], dtype=object)

We are going to split this dataset in two separate data .
One with the columns **"age"** and **"gender"**, which we referred to as input set  and the other with the last column **"genre"** that is the output set.
The output set contains the predictions.

In [ ]:
# To view a specific column from a Pandas DataFrame
music_df.genre
# print(music_df['genre'])

0         Pop
1         Pop
2        Jazz
3        Rock
4         Pop
         ...
70124     Pop
70125     Pop
70126     Pop
70127     Pop
70128     Pop
Name: genre, Length: 70129, dtype: object

In [ ]:
# to see specific column
desired_input_columns = ['age', 'gender'] # Create a list of the columns I want to keep
input_dataset = music_df[desired_input_columns]
print(input_dataset)

       age  gender
0       35  Female
1       45    Male
2       35   Other
3       45    Male
4       45    Male
...    ...     ...
70124   35    Male
70125   55  Female
70126   55    Male
70127   35    Male
70128   35  Female

[70129 rows x 2 columns]

In [ ]:
# input_dataset = music_df.loc[:, ['age', 'gender']] # : The colon is a slice operator that means "select all". When it is placed before the comma, it tells .loc[] to select all rows.
# input_dataset

In [ ]:
# input_dataset = music_df.loc[4, 'gender'] # specific row and column to retrieve a specific value
# print(input_dataset)

In [ ]:
#Label Encoding
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# input_dataset['gender'] = le.fit_transform(input_dataset['gender'])
# print(input_dataset)

In [ ]:
# # Reverse (decode) back to original
# input_dataset['gender'] = le.inverse_transform(input_dataset['gender'])
# print(input_dataset)

In [ ]:
# One-hot encode the 'gender' column (drop_first=True to avoid multicollinearity, optional for trees)
input_dataset = pd.get_dummies(input_dataset, columns=['gender'], drop_first=True)
print(input_dataset)

       age  gender_Male  gender_Other
0       35        False         False
1       45         True         False
2       35        False          True
3       45         True         False
4       45         True         False
...    ...          ...           ...
70124   35         True         False
70125   55        False         False
70126   55         True         False
70127   35         True         False
70128   35        False         False

[70129 rows x 3 columns]

In [ ]:
output_dataset = music_df['genre']
print(output_dataset)

0         Pop
1         Pop
2        Jazz
3        Rock
4         Pop
         ...
70124     Pop
70125     Pop
70126     Pop
70127     Pop
70128     Pop
Name: genre, Length: 70129, dtype: object

we need to split the data sets into two sets.
One for training and another for testing.The usual rule is to allocate 70% to 80% of the data for training and the other 20% to 30% for testing.

First we import the "train_test_split" function from the "sklearn.model_selection" module.
This function takes tree arguments the input data set "X" , the output data set "y", and a parameter to specify the size of the test dataset "test_size".
This function returns a tuple, so we can unpack this tuple to four variables.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_dataset, output_dataset, test_size=0.2)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

# Now we have a model , we need to train it to learn patterns in the dataset. To do that we call the method ".fit()". This method takes two dataset, the input and the output.
model.fit(X_train, y_train)

DecisionTreeClassifier()

Next we need to ask our model to make a prediction. To do that we call the ".predict()" method. This method takes a two dimensional array.
In this two dimensional array each element is an array, we pass a new input set.
In our case we are passing two inputs simultaneously.
**A 21 year old male and a 22 year old female. We put the result in a variable called predictions.**

**predictions = model.predict( [ [21, 1], [22, 0] ] )**

In [ ]:
predictions = model.predict(X_test)
print(predictions)

['Pop' 'Pop' 'Pop' ... 'Pop' 'Pop' 'Pop']

Now to calculate the accuracy we import **"accuracy_score()"** function from the **"sklearn.metrics"** module.
The **"accuracy_score()"** takes two methods,the output test dataset**"y_test" **and **our predictions** and returns an accuracy score between 0 to 1.
We store the result in the variable "model_score"

In [ ]:
from sklearn.metrics import accuracy_score
model_score = accuracy_score(y_test, predictions)
print(model_score)

0.6041636959931556

In [ ]:
# # to see specific column
# desired_input_columns = ['age', 'gender','genre'] # Create a list of the columns I want to keep
# input_dataset = music_df[desired_input_columns]
# print(input_dataset)

In [ ]:
# predictions = model.predict( [ [45, 1], [45, 0] ] )
# print(predictions)